/**
 * Elenco delle lingue supportate dal widget di traduzione automatica.
 * Ogni voce contiene: codice Google Translate, nome nella lingua stessa (name),
 * nome comune in italiano/inglese per la ricerca (alt), bandiera (emoji).
 * L'elenco viene ordinato alfabeticamente a runtime da main.js in base al nome nativo.
 */
const SITE_LANGUAGES = [
  { code: "it", name: "Italiano", alt: "Italian", flag: "🇮🇹" },
  { code: "af", name: "Afrikaans", alt: "Afrikaans", flag: "🇿🇦" },
  { code: "sq", name: "Shqip", alt: "Albanese, Albanian", flag: "🇦🇱" },
  { code: "am", name: "አማርኛ", alt: "Amarico, Amharic", flag: "🇪🇹" },
  { code: "ar", name: "العربية", alt: "Arabo, Arabic", flag: "🇸🇦" },
  { code: "hy", name: "Հայերեն", alt: "Armeno, Armenian", flag: "🇦🇲" },
  { code: "az", name: "Azərbaycan dili", alt: "Azero, Azerbaijani", flag: "🇦🇿" },
  { code: "eu", name: "Euskara", alt: "Basco, Basque", flag: "🏴" },
  { code: "be", name: "Беларуская", alt: "Bielorusso, Belarusian", flag: "🇧🇾" },
  { code: "bn", name: "বাংলা", alt: "Bengalese, Bangla, Bengali", flag: "🇧🇩" },
  { code: "bs", name: "Bosanski", alt: "Bosniaco, Bosnian", flag: "🇧🇦" },
  { code: "bg", name: "Български", alt: "Bulgaro, Bulgarian", flag: "🇧🇬" },
  { code: "ca", name: "Català", alt: "Catalano, Catalan", flag: "🏴" },
  { code: "ceb", name: "Cebuano", alt: "Cebuano", flag: "🇵🇭" },
  { code: "zh-CN", name: "中文（简体）", alt: "Cinese semplificato, Chinese Simplified", flag: "🇨🇳" },
  { code: "zh-TW", name: "中文（繁體）", alt: "Cinese tradizionale, Chinese Traditional", flag: "🇹🇼" },
  { code: "co", name: "Corsu", alt: "Corso, Corsican", flag: "🇫🇷" },
  { code: "hr", name: "Hrvatski", alt: "Croato, Croatian", flag: "🇭🇷" },
  { code: "cs", name: "Čeština", alt: "Ceco, Czech", flag: "🇨🇿" },
  { code: "da", name: "Dansk", alt: "Danese, Danish", flag: "🇩🇰" },
  { code: "nl", name: "Nederlands", alt: "Olandese, Dutch", flag: "🇳🇱" },
  { code: "en", name: "English", alt: "Inglese, English", flag: "🇬🇧" },
  { code: "eo", name: "Esperanto", alt: "Esperanto", flag: "🌐" },
  { code: "et", name: "Eesti", alt: "Estone, Estonian", flag: "🇪🇪" },
  { code: "fi", name: "Suomi", alt: "Finlandese, Finnish", flag: "🇫🇮" },
  { code: "fr", name: "Français", alt: "Francese, French", flag: "🇫🇷" },
  { code: "fy", name: "Frysk", alt: "Frisone, Frisian", flag: "🇳🇱" },
  { code: "gl", name: "Galego", alt: "Galiziano, Galician", flag: "🏴" },
  { code: "ka", name: "ქართული", alt: "Georgiano, Georgian", flag: "🇬🇪" },
  { code: "de", name: "Deutsch", alt: "Tedesco, German", flag: "🇩🇪" },
  { code: "el", name: "Ελληνικά", alt: "Greco, Greek", flag: "🇬🇷" },
  { code: "gu", name: "ગુજરાતી", alt: "Gujarati", flag: "🇮🇳" },
  { code: "ht", name: "Kreyòl ayisyen", alt: "Creolo haitiano, Haitian Creole", flag: "🇭🇹" },
  { code: "ha", name: "Hausa", alt: "Hausa", flag: "🇳🇬" },
  { code: "haw", name: "ʻŌlelo Hawaiʻi", alt: "Hawaiano, Hawaiian", flag: "🇺🇸" },
  { code: "he", name: "עברית", alt: "Ebraico, Hebrew", flag: "🇮🇱" },
  { code: "hi", name: "हिन्दी", alt: "Hindi", flag: "🇮🇳" },
  { code: "hmn", name: "Hmoob", alt: "Hmong", flag: "🌐" },
  { code: "hu", name: "Magyar", alt: "Ungherese, Hungarian", flag: "🇭🇺" },
  { code: "is", name: "Íslenska", alt: "Islandese, Icelandic", flag: "🇮🇸" },
  { code: "ig", name: "Igbo", alt: "Igbo", flag: "🇳🇬" },
  { code: "id", name: "Bahasa Indonesia", alt: "Indonesiano, Indonesian", flag: "🇮🇩" },
  { code: "ga", name: "Gaeilge", alt: "Irlandese, Irish", flag: "🇮🇪" },
  { code: "ja", name: "日本語", alt: "Giapponese, Japanese", flag: "🇯🇵" },
  { code: "jv", name: "Basa Jawa", alt: "Giavanese, Javanese", flag: "🇮🇩" },
  { code: "kn", name: "ಕನ್ನಡ", alt: "Kannada", flag: "🇮🇳" },
  { code: "kk", name: "Қазақ тілі", alt: "Kazako, Kazakh", flag: "🇰🇿" },
  { code: "km", name: "ខ្មែរ", alt: "Khmer", flag: "🇰🇭" },
  { code: "rw", name: "Ikinyarwanda", alt: "Kinyarwanda", flag: "🇷🇼" },
  { code: "ko", name: "한국어", alt: "Coreano, Korean", flag: "🇰🇷" },
  { code: "ku", name: "Kurdî", alt: "Curdo, Kurdish", flag: "🌐" },
  { code: "ky", name: "Кыргызча", alt: "Kirghiso, Kyrgyz", flag: "🇰🇬" },
  { code: "lo", name: "ລາວ", alt: "Lao", flag: "🇱🇦" },
  { code: "la", name: "Latina", alt: "Latino, Latin", flag: "🏛️" },
  { code: "lv", name: "Latviešu", alt: "Lettone, Latvian", flag: "🇱🇻" },
  { code: "lt", name: "Lietuvių", alt: "Lituano, Lithuanian", flag: "🇱🇹" },
  { code: "lb", name: "Lëtzebuergesch", alt: "Lussemburghese, Luxembourgish", flag: "🇱🇺" },
  { code: "mk", name: "Македонски", alt: "Macedone, Macedonian", flag: "🇲🇰" },
  { code: "mg", name: "Malagasy", alt: "Malgascio, Malagasy", flag: "🇲🇬" },
  { code: "ms", name: "Bahasa Melayu", alt: "Malese, Malay", flag: "🇲🇾" },
  { code: "ml", name: "മലയാളം", alt: "Malayalam", flag: "🇮🇳" },
  { code: "mt", name: "Malti", alt: "Maltese", flag: "🇲🇹" },
  { code: "mi", name: "Māori", alt: "Maori", flag: "🇳🇿" },
  { code: "mr", name: "मराठी", alt: "Marathi", flag: "🇮🇳" },
  { code: "mn", name: "Монгол", alt: "Mongolo, Mongolian", flag: "🇲🇳" },
  { code: "my", name: "မြန်မာ", alt: "Birmano, Burmese", flag: "🇲🇲" },
  { code: "ne", name: "नेपाली", alt: "Nepalese, Nepali", flag: "🇳🇵" },
  { code: "no", name: "Norsk", alt: "Norvegese, Norwegian", flag: "🇳🇴" },
  { code: "ny", name: "Chichewa", alt: "Chichewa, Nyanja", flag: "🇲🇼" },
  { code: "or", name: "ଓଡ଼ିଆ", alt: "Odia", flag: "🇮🇳" },
  { code: "ps", name: "پښتو", alt: "Pashto", flag: "🇦🇫" },
  { code: "fa", name: "فارسی", alt: "Persiano, Persian, Farsi", flag: "🇮🇷" },
  { code: "pl", name: "Polski", alt: "Polacco, Polish", flag: "🇵🇱" },
  { code: "pt", name: "Português", alt: "Portoghese, Portuguese", flag: "🇵🇹" },
  { code: "pa", name: "ਪੰਜਾਬੀ", alt: "Punjabi", flag: "🇮🇳" },
  { code: "ro", name: "Română", alt: "Rumeno, Romanian", flag: "🇷🇴" },
  { code: "ru", name: "Русский", alt: "Russo, Russian", flag: "🇷🇺" },
  { code: "sm", name: "Gagana Samoa", alt: "Samoano, Samoan", flag: "🇼🇸" },
  { code: "gd", name: "Gàidhlig", alt: "Gaelico scozzese, Scots Gaelic", flag: "🏴" },
  { code: "sr", name: "Српски", alt: "Serbo, Serbian", flag: "🇷🇸" },
  { code: "st", name: "Sesotho", alt: "Sesotho", flag: "🇱🇸" },
  { code: "sn", name: "ChiShona", alt: "Shona", flag: "🇿🇼" },
  { code: "sd", name: "سنڌي", alt: "Sindhi", flag: "🇵🇰" },
  { code: "si", name: "සිංහල", alt: "Singalese, Sinhala", flag: "🇱🇰" },
  { code: "sk", name: "Slovenčina", alt: "Slovacco, Slovak", flag: "🇸🇰" },
  { code: "sl", name: "Slovenščina", alt: "Sloveno, Slovenian", flag: "🇸🇮" },
  { code: "so", name: "Soomaali", alt: "Somalo, Somali", flag: "🇸🇴" },
  { code: "es", name: "Español", alt: "Spagnolo, Spanish", flag: "🇪🇸" },
  { code: "su", name: "Basa Sunda", alt: "Sundanese", flag: "🇮🇩" },
  { code: "sw", name: "Kiswahili", alt: "Swahili", flag: "🇰🇪" },
  { code: "sv", name: "Svenska", alt: "Svedese, Swedish", flag: "🇸🇪" },
  { code: "tl", name: "Filipino", alt: "Filippino, Tagalog", flag: "🇵🇭" },
  { code: "tg", name: "Тоҷикӣ", alt: "Tagiko, Tajik", flag: "🇹🇯" },
  { code: "ta", name: "தமிழ்", alt: "Tamil", flag: "🇮🇳" },
  { code: "tt", name: "Татар", alt: "Tataro, Tatar", flag: "🌐" },
  { code: "te", name: "తెలుగు", alt: "Telugu", flag: "🇮🇳" },
  { code: "th", name: "ไทย", alt: "Thailandese, Thai", flag: "🇹🇭" },
  { code: "tr", name: "Türkçe", alt: "Turco, Turkish", flag: "🇹🇷" },
  { code: "tk", name: "Türkmen", alt: "Turkmeno, Turkmen", flag: "🇹🇲" },
  { code: "uk", name: "Українська", alt: "Ucraino, Ukrainian", flag: "🇺🇦" },
  { code: "ur", name: "اردو", alt: "Urdu", flag: "🇵🇰" },
  { code: "ug", name: "ئۇيغۇرچە", alt: "Uiguro, Uyghur", flag: "🌐" },
  { code: "uz", name: "Oʻzbek", alt: "Uzbeco, Uzbek", flag: "🇺🇿" },
  { code: "vi", name: "Tiếng Việt", alt: "Vietnamita, Vietnamese", flag: "🇻🇳" },
  { code: "cy", name: "Cymraeg", alt: "Gallese, Welsh", flag: "🏴" },
  { code: "xh", name: "isiXhosa", alt: "Xhosa", flag: "🇿🇦" },
  { code: "yi", name: "ייִדיש", alt: "Yiddish", flag: "🌐" },
  { code: "yo", name: "Yorùbá", alt: "Yoruba", flag: "🇳🇬" },
  { code: "zu", name: "isiZulu", alt: "Zulu", flag: "🇿🇦" }
];
